# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag']},
        ),
        migrations.AddField(
            model_name='seller',
            name='auto_catg',
            field=models.ForeignKey(blank=True, help_text='Automatic category to apply to an expense.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='bank.Category'),
        ),
        migrations.AddField(
            model_name='seller',
            name='auto_tags',
            field=models.ManyToManyField(blank=True, help_text='Automatic tags to apply to an expense', related_name='sellers', to='bank.Tag'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='expenses', to='bank.Tag'),
        ),
    ]
