# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20170814_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='pref_account',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='pref_paytype',
        ),
    ]
