# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_auto_20170816_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
