# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_auto_20170816_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='rank',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
