# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_location_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['rank', 'seller', 'loc_name']},
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='pref_account',
            new_name='pref_accounts',
        ),
        migrations.AddField(
            model_name='order',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
