# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_auto_20170820_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='invoiceid',
            field=models.CharField(blank=True, default='', help_text='Used to track OrderId for expenses without creating an order', max_length=32),
        ),
    ]
