# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_expense_invoiceid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='pref_accounts',
        ),
    ]
