# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-05 17:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0010_remove_seller_pref_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=7)),
                ('balance_date', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='bank.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Timecard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateTimeField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timecards', to='bank.Source')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timecards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-work_date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='timecard',
            unique_together=set([('user', 'source', 'work_date')]),
        ),
        migrations.AlterUniqueTogether(
            name='accountbalance',
            unique_together=set([('account', 'balance_date')]),
        ),
    ]
